### PR TITLE
[Issue-128] Reuse vertx client connection pool

### PR DESCRIPTION
**Pull request by gaol**
[[Issue-125](https://github.com/vert-x3/vertx-mail-client/issues/125)] Make the distinction between the resource context and the caller context
[[Issue-128](https://github.com/vert-x3/vertx-mail-client/issues/128)] Reuse vertx client connection pool

* Use `io.vertx.core.net.impl.clientconnection.Pool` for the connection pool management
* Futurised implementations to use new connection pool easily
* Update SMTPConnection and MultilineParser to have queue of waiting handlers
* Leave leagcy method in SMTPConnectionPool for tests and keep the contract unmodified
* Distinct the resource context and the caller context following Vert.x 4 context model
   * https://github.com/vert-x3/wiki/wiki/RFC:-Vert.x-4-context-model

I did not use ConnectionManager because of the following reason:
* The Endpoint will be disposed when there is no pending requests and open connections, which leads to pool level variables un applicable, like the default auth method. 

Motivation:

Fixes: #128 
Fixes: #125

### CODE REVIEW

**Comment by gaol** [comment]
@vietj  @pmlopes could you please review? Thanks :)

**Comment by pmlopes** [comment]
One comment, all the `log.debug("methodName()");` probably should be at the trace level as I think if you're doing it it is because you're trying to trace back where some call is going wrong. Plus many people use `debug` to print their own debug info so this would be lots of stuff going to the logs.

**Comment by gaol** [comment]
@pmlopes Thanks for the checking, it makes sense to use `trace`, I updated the log level as suggested :)

**Comment by vietj** [comment]
I can see this PR handles several concerns (including the connection pool), can we have them addressed in separate PR's so it is possible to review them ?

**Comment by gaol** [comment]
@vietj OK, I will try to split it to several PRs :)

**Comment by gaol** [comment]
@vietj I don't think it can catch up the `milestone-5` release to split the PRs and merged them one by one. I am working on it, it is OK to leave it for next release.

**Comment by vietj** [comment]
sure, from now on we will do more frequent releases of master

**Comment by gaol** [comment]
Close it by rescheduling it to 4.1.0 milestone because there will be changes in the connection pool in core.

**Pull request closed without merging**
