### PR TITLE
Merge wip branch, this is mostly the refactorings branch from Tim merged with the master changes for Ruby from Julien

### PR DESCRIPTION
**Pull request by alexlehm**

### CODE REVIEW

**Comment by purplefox** [comment]
Alex, I'm confused about what you've done here.. can you explain?

Looks like you've merged something into master without review?

**Comment by purplefox** [comment]
Uhh, this is going to be too complex to undo and redo so I'm going just going to let it pass this time.

But please, next time, when you are ready to merge new work into master, submit a PR and get someone to review it. Even I don't merge stuff into master more than a few lines without review ;)

Please read this https://github.com/vert-x3/wiki/wiki/Development-Process :)

**Comment by alexlehm** [comment]
the new pr was basically your pr merged to the current master, I created a new wip branch based on that. I had reviewed that yesterday evening. I added a few comments and a few text corrections to the branch and then merged that into master.

**Comment by alexlehm** [comment]
the changes are the ones from pr https://github.com/vert-x3/vertx-mail-client/commit/623722e62c59ed310e458ad413673127a035afa4 and then mine https://github.com/vert-x3/vertx-mail-client/compare/623722e62c59ed310e458ad413673127a035afa4...87a19dafcbe1b987b983b73e969e098ffcec25a3

**Pull request merged**
