### PR TITLE
FIX#219: bare <LF> received after DATA

### LINKED ISSUE #219: bare <LF> received after DATA
When sending Mails with longer Header Values, a "newer" Postfix Server will Reject Mail Submission due to a `bare <LF> received after DATA` Error.

This happens because the Recipient List will be splitted after >=75 chars by just adding a single `\n` instead of `\r\n`.

I Plan to add a PR to correct this behavior.
In the [io.vertx.ext.mail.mailencoder.Utils](https://github.com/vert-x3/vertx-mail-client/blob/master/src/main/java/io/vertx/ext/mail/mailencoder/Utils.java) class are some more places where just a single LineFeed is added.

### Version

Which version(s) did you encounter this bug ?
`3.5.3+`

### Context

[SMTP Smuggling](https://www.postfix.org/smtp-smuggling.html)

### Do you have a reproducer?

Send Mails with a long Subject/Recepient List.

* https://gist.github.com/cs8898/b740ee29206d5b9f7bee7c352d676086

The Gist contains Two Dumps of the RAW SNMP Messages, one from vertx and the other one from Thunderbird.  
Thunderbird encodes all as `\r\n`.

### Relevant class

[io.vertx.ext.mail.mailencoder.Utils](https://github.com/vert-x3/vertx-mail-client/blob/master/src/main/java/io/vertx/ext/mail/mailencoder/Utils.java)

### PR DESCRIPTION
**Pull request by cs8898**
## Motivation:

fixes #219  SMTP Smuggling problems

## Additional References:

https://cr.yp.to/docs/smtplf.html
https://www.postfix.org/smtp-smuggling.html

## Solution:

Replace `\n` in Headers by `\r\n` before sending.

## Msg Dumps for Reference:

https://gist.github.com/cs8898/b740ee29206d5b9f7bee7c352d676086

## Test:

* [x] Tested with my Quarkus Project (Postfix 3.5.23)

### CODE REVIEW

**Comment by vietj** [comment]
can you add a test for this

**Comment by cs8898** [comment]
Yah, i plan to modify the replacement to be more in the style of message body sending. (Split on \n and add to the SB)

Should i also drop the assert, because theoreticaly the encoder won't add any \r.

For testing i would add a long recipient list, long subject and a long message text as single line.

Should i edit the test-helper class, so the bare LF check can be triggered by a flag?

**Comment by cs8898** [comment]
# BareLF Detection

The implementation is based on the Postfix logic.
When a `\n` is read the preceeded character must be a `\r` otherwise it will fail with `bare <LF>`.

## Postfix 3.8.5

https://github.com/vdukhovni/postfix/blob/9d037ea08042ef5aac7510600ccb1a9541411b4c/postfix/src/global/smtp_stream.c#L431-L442

## Postfix 3.5.23

https://github.com/vdukhovni/postfix/blob/f75140fe8504f1fa69e98facbf8258b67af7ebff/postfix/src/global/smtp_stream.c#L414-L427

**Comment by cs8898** [comment]
closed in favor of #221

**Pull request closed without merging**
